# -*- coding: utf-8 -*-
"""Besoin_Client2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1atyOJoHxtUUBS-qOe0A2QHQ00sN33qim

###Script automatisé
"""

import pandas as pd
import joblib
import numpy as np

# Charger les modèles préenregistrés
model = joblib.load('final_random_forest_model.pkl')
label_encoder = joblib.load('label_encoder.pkl')

# Définir les plages réalistes (à ajuster selon ton dataset)
value_ranges = {
    'Length': (0, 400),    # Longueur en mètres
    'Draft': (0, 20),      # Tirant d'eau en mètres
    'SOG': (0, 30),        # Speed Over Ground en nœuds (0 à 30 nœuds typique)
    'Width': (0, 60)       # Largeur en mètres (0 à 60 m, basé sur navires typiques)
}

# Fonction pour obtenir une entrée valide
def get_valid_input(prompt, data_type, range_min_max):
    while True:
        try:
            value = data_type(input(prompt))
            if not (range_min_max[0] <= value <= range_min_max[1]):
                print(f"Erreur : {value} est hors de la plage [{range_min_max[0]}, {range_min_max[1]}]. Veuillez réessayer.")
                continue
            return value
        except ValueError:
            print("Erreur : Veuillez entrer un nombre valide.")

# Collecter les données
print("Veuillez entrer les caractéristiques du navire :")
data = {
    'Length': get_valid_input("Longueur (m) [0-400] : ", float, value_ranges['Length']),
    'Draft': get_valid_input("Tirant d'eau (m) [0-20] : ", float, value_ranges['Draft']),
    'SOG': get_valid_input("Vitesse (nœuds) [0-30] : ", float, value_ranges['SOG']),
    'Width': get_valid_input("Largeur (m) [0-60] : ", float, value_ranges['Width'])
}

# Convertir en DataFrame
new_data = pd.DataFrame([data])
new_data = new_data.fillna(new_data.median())

# Prédire
predictions_encoded = model.predict(new_data)
predictions = label_encoder.inverse_transform(predictions_encoded)
predicted_type = predictions[0]
print(f"\nType de navire prédit : {predicted_type}")